import Head from 'next/head';
import styles from '@/styles/Home.module.css';

export default function Home(props) {
  console.log(props);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Homepage</h1>
    </>
  );
}
export async function getServerSideProps(context) {
  let res = await fetch('http://localhost:3000/api/users', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  });
  let allPosts = await res.json();

  return {
    props: { allPosts },
  };
}
